# Generated by Django 2.1.dev20180318005124 on 2018-04-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20180404_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='tag',
        ),
        migrations.AddField(
            model_name='picture',
            name='tag',
            field=models.ManyToManyField(to='photos.Tag'),
        ),
    ]
